services:
  cloudflared-gotify:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-gotify
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
