services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    labels:
      - "snadboy.revp.8080.domain=sabnzbd.isnadboy.com"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - sabnzbd-data:/config
      - /mnt/docker/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  sabnzbd-data:
    external: true
