services:
  cloudflare-overseerr:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-overseerr
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
