all:
  children:
    pve_nodes:
      hosts:
        pve-colossus:
          ansible_user: root
        pve-guardian:
          ansible_user: root
        pve-multivac:
          ansible_user: root
    pbs_servers:
      hosts:
        host-svalbard.isnadboy.com:
          ansible_user: root
        host-alexandria.isnadboy.com:
          ansible_user: root
    ubuntu_vms:
      hosts:
        host-arr.isnadboy.com:
          ansible_user: snadboy
        host-cadre.isnadboy.com:
          ansible_user: snadboy
        host-plex.isnadboy.com:
          ansible_user: snadboy
        host-iot.isnadboy.com:
          ansible_user: snadboy
        host-utilities.isnadboy.com:
          ansible_user: snadboy
        host-ansible-controller.isnadboy.com:
          ansible_user: snadboy
          ansible_connection: local
    debian_containers:
      hosts:
        host-ns.isnadboy.com:
          ansible_user: root
    lxc_containers:
      # Managed via pct exec delegated to parent PVE node (no SSH)
      hosts:
        ns-secundus:
          pve_host: pve-guardian
          pve_vmid: 108
        ns-tertius:
          pve_host: pve-multivac
          pve_vmid: 112
        pve-scripts-local:
          pve_host: pve-colossus
          pve_vmid: 104
    apt_hosts:
      children:
        pve_nodes:
        pbs_servers:
        ubuntu_vms:
        debian_containers:
  vars:
    ansible_become: true
    ansible_become_method: sudo
