services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 8083:80
    labels:
      - "snadboy.revp.80.domain=gotify.isnadboy.com,gotify.snadboy.com"
    environment:
      - TZ=America/Chicago
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS:-appleButter}
    volumes:
      - /mnt/docker/gotify/app-data:/app/data
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    name: ${NETWORK_NAME:-gotify_default}
    external: ${NETWORK_EXTERNAL:-false}
