services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3500:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - HOMEPAGE_VAR_TITLE=Homelab Dashboard
      - LOG_TARGETS=stdout
      - HOMEPAGE_ALLOWED_HOSTS=homepage.isnadboy.com
      - HOMEPAGE_VAR_PLEX_TOKEN=js1SqwFxuN2eirNGdeox
      - HOMEPAGE_VAR_TAUTULLI_KEY=a9e9e9242f0c4ea8a0990c56dd62ce40
      - HOMEPAGE_VAR_PROXMOX_USER=homepage@pve!homepage-token
      - HOMEPAGE_VAR_PROXMOX_TOKEN=16e2f699-b719-4017-9dd6-4ca487594dc7
      - HOMEPAGE_VAR_PBS_ALEXANDRIA_USER=homepage@pbs!homepage-token
      - HOMEPAGE_VAR_PBS_ALEXANDRIA_TOKEN=3260a33e-23b8-4fed-bd31-878c6077afd4
      - HOMEPAGE_VAR_PBS_SVALBARD_USER=homepage@pbs!homepage-token
      - HOMEPAGE_VAR_PBS_SVALBARD_TOKEN=51b3d340-272c-487c-b100-6dc274caf30f
      - HOMEPAGE_VAR_CLOUD_PBS_USER=9094815d6a404b2ca0a6@pbs!homepage-token
      - HOMEPAGE_VAR_CLOUD_PBS_TOKEN=9bf2dfba-d1fd-477b-8690-75d495881c5a
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "snadboy.revp.3000.domain=homepage.isnadboy.com"

volumes:
  homepage-config:
    external: true
