services:
  agregarr:
    image: agregarr/agregarr:latest
    container_name: agregarr
    labels:
      - "snadboy.revp.7171.domain=agregarr.isnadboy.com"
    volumes:
      - agregarr-data:/app/config
    ports:
      - 7171:7171
    restart: unless-stopped
    networks:
      - app_network

volumes:
  agregarr-data:
    external: true

networks:
  app_network:
    name: ${NETWORK_NAME:-agregarr_default}
    external: ${NETWORK_EXTERNAL:-false}
