services:
  agregarr:
    image: agregarr/agregarr:latest
    container_name: agregarr
    labels:
      - "snadboy.revp.7171.domain=agregarr.isnadboy.com"
    volumes:
      - agregarr-data:/app/config
      - /mnt/media/TV Shows/.placeholders:/placeholders/tv
      - /mnt/media/Movies/.placeholders:/placeholders/movies
    ports:
      - 7171:7171
    restart: unless-stopped

volumes:
  agregarr-data:
    external: true
