services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    labels:
      - "snadboy.revp.6767.domain=bazarr.isnadboy.com"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - bazarr-data:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/TV Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  bazarr-data:
    external: true
