services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    labels:
      - "snadboy.revp.3000.domain=semaphore.isnadboy.com"
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD:-changeme}
      - SEMAPHORE_ADMIN_NAME=Admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_PLAYBOOK_PATH=/etc/semaphore
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ENCRYPTION_KEY:-}
    volumes:
      - semaphore-data:/etc/semaphore
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  semaphore-data:
    external: true
